export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_MULTIPLE_CUIT = "LOGIN_MULTIPLE_CUIT"
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_CLAVE_EXPIRADA = "LOGIN_CLAVE_EXPIRADA";
export const SUCCESSPASS = "SUCCESSPASS";
export const LOGOUT = "LOGOUT";


/**mensajeria */
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

/* clave */
export const USUARIO_INVALIDO = "USUARIO_INVALIDO";
export const CLAVE_INVALIDA = "CLAVE_INVALIDA";

/*Recupero*/

export const RECUPERO_USUARIO = "RECUPERO_USUARIO"
export const OLVIDO_BLOQUEO = "OLVIDO_BLOQUEO"
export const METODOS_VALIDOS = "METODOS_VALIDOS"
export const RECUPERO_SUCCESS = "RECUPERO_SUCCESS"
export const METODOS_VALIDOS_INVOCADO = "METODOS_VALIDOS_INVOCADO"